# Generated by Django 4.2.1 on 2023-05-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.ImageField(null=True, upload_to='tourismtypes/'),
        ),
    ]
