# Generated by Django 4.2.1 on 2023-05-25 13:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_type_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='touroperator',
            name='content',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='type',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
