# Generated by Django 4.2.1 on 2023-05-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_interestingfacts_facts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('touroperator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operatorimages', to='core.touroperator')),
            ],
        ),
    ]
