# Generated by Django 4.2.1 on 2023-05-25 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='touroperator',
        ),
        migrations.AddField(
            model_name='image',
            name='attraction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractionimages', to='core.attraction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='attractions/'),
        ),
        migrations.CreateModel(
            name='OperatorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='touroperators/')),
                ('touroperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operatorimages', to='core.touroperator')),
            ],
        ),
        migrations.CreateModel(
            name='HotelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='hotels/')),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotelimages', to='core.hotel')),
            ],
        ),
    ]
