# Generated by Django 4.2.1 on 2023-05-26 04:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_image_touroperator_image_attraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='touroperators/')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('touroperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operatorservices', to='core.touroperator')),
            ],
        ),
    ]
