# Generated by Django 4.2.1 on 2023-05-26 13:47

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_operatorservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='touroperators/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('touroperator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operatorpackages', to='core.touroperator')),
            ],
        ),
        migrations.DeleteModel(
            name='OperatorService',
        ),
    ]
