# Generated by Django 4.2.1 on 2023-05-27 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_operatorpackage_delete_operatorservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttractionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('attraction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attractionfees', to='core.attraction')),
            ],
        ),
    ]
