# Generated by Django 4.2.1 on 2023-05-27 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_hotel_price_per_day_room_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(null=True, upload_to='hotels/'),
        ),
    ]
